
services:
  api:
    build:
      context: ./app
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: >
      sh -c "
      python manage.py createsuperuser &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - 8000:8000
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: app/docker/docker_files/Dockerfile_app
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 5000:5000

volumes:
  db_data:

