# Generated by Django 5.1.3 on 2024-11-18 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], max_length=10)),
                ('departemen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.departemen')),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.jabatan')),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=10)),
                ('gaji_pokok', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tunjangan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potongan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gaji', models.DecimalField(decimal_places=2, max_digits=10)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu_masuk', models.TimeField(blank=True, null=True)),
                ('waktu_keluar', models.TimeField(blank=True, null=True)),
                ('status_absensi', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha')], max_length=10)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.karyawan')),
            ],
        ),
    ]
